apiVersion: v1
kind: Secret
metadata:
  name: {{ include "users-services.fullname" . }}
type: Opaque
data:
  {{- range .Values.secret.values }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
