apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.volume.logging.name}}
  labels:
    app: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.volume.logging.size}}
  storageClassName: {{.Values.volume.logging.storageClassName}}
